# Generated by Django 4.2.7 on 2023-12-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='about_you',
        ),
    ]
